load("@rules_python//python:defs.bzl", "py_binary")
load("@pypi//:requirements.bzl", "requirement")

py_binary(
  name = "solve01",
  srcs = ["solve01.py"],
  args = ["$(location :data/01.txt)"],
  data = ['data/01.txt'],
)

py_binary(
  name = "solve02",
  srcs = ["solve02.py"],
  args = ["$(location :data/02.txt)"],
  data = ['data/02.txt'],
)

py_binary(
  name = "solve03",
  srcs = ["solve03.py"],
  args = ["$(location :data/03.txt)"],
  data = ['data/03.txt'],
)

py_binary(
  name = "solve04",
  srcs = ["solve04.py"],
  args = ["$(location :data/04.txt)"],
  data = ['data/04.txt'],
  deps = [
    requirement("more-itertools"),
  ]
)

py_binary(
  name = "solve05",
  srcs = ["solve05.py"],
  args = ["$(location :data/05.txt)"],
  data = ['data/05.txt'],
)

py_binary(
  name = "solve06",
  srcs = ["solve06.py"],
  args = ["$(location :data/06.txt)"],
  data = ['data/06.txt'],
)

py_binary(
  name = "solve07",
  srcs = ["solve07.py"],
  args = ["$(location :data/07.txt)"],
  data = ['data/07.txt'],
)

py_binary(
  name = "solve08",
  srcs = ["solve08.py"],
  args = ["$(location :data/08.txt)"],
  data = ['data/08.txt'],
)

py_binary(
  name = "solve09",
  srcs = ["solve09.py"],
  args = ["$(location :data/09.txt)"],
  data = ['data/09.txt'],
)

py_binary(
  name = "solve10",
  srcs = ["solve10.py"],
  args = ["$(location :data/10.txt)"],
  data = ['data/10.txt'],
)

py_binary(
  name = "solve11",
  srcs = ["solve11.py"],
  args = ["$(location :data/11.txt)"],
  data = ['data/11.txt'],
)

py_binary(
  name = "solve12",
  srcs = ["solve12.py"],
  args = ["$(location :data/12.txt)"],
  data = ['data/12.txt'],
)

py_binary(
  name = "solve13",
  srcs = ["solve13.py"],
  args = ["$(location :data/13.txt)"],
  data = ['data/13.txt'],
)

py_binary(
  name = "solve14",
  srcs = ["solve14.py"],
  args = ["$(location :data/14.txt)"],
  data = ['data/14.txt'],
)
